.PHONY: test bench lint

test:
	CGO_ENABLED=0 go test ./...

bench:
	CGO_ENABLED=0 go test -run '^$$' -bench . -benchmem ./...

lint:
	test -z "$$(gofmt -l $$(rg --files -g '*.go' -g '!conformance/corpus/**'))"
	CGO_ENABLED=0 go vet ./...
	golangci-lint run ./...
